service: serverless-recipe-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    lambda: true
    apiGateway: true

custom:
  recipeItemsTable: recipeItemsTable-${self:provider.stage}

functions:

  RS256Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetRecipeItems:
    handler: src/lambda/http/getRecipeItems.handler
    events:
      - http:
          method: get
          path: recipes
          cors: true
          authorizer: RS256Auth
    environment:
      RECIPE_ITEMS_TABLE: ${self:custom.recipeItemsTable}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.recipeItemsTable}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"

  CreateRecipeItem:
    handler: src/lambda/http/createRecipeItem.handler
    events:
      - http:
          method: post
          path: recipes
          cors: true
          authorizer: RS256Auth
          request:
            schema:
              application/json: ${file(schemas/create-update-recipe-item-request.json)}
    environment:
      RECIPE_ITEMS_TABLE: ${self:custom.recipeItemsTable}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.recipeItemsTable}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"

  UpdateRecipeItem:
    handler: src/lambda/http/updateRecipeItem.handler
    events:
      - http:
          method: patch
          path: recipes/{recipeId}
          cors: true
          authorizer: RS256Auth
          request:
            schema:
              application/json: ${file(schemas/create-update-recipe-item-request.json)}
    environment:
      RECIPE_ITEMS_TABLE: ${self:custom.recipeItemsTable}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.recipeItemsTable}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi  # refers to the resource created by cloudformation stack if there is a function which uses the api gateway.

    RecipeItemsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: recipeId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: recipeId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TableName: ${self:custom.recipeItemsTable}
